//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Districts = new HashSet<District>();
            this.Drugstores = new HashSet<Drugstore>();
            this.Drugstores1 = new HashSet<Drugstore>();
            this.DrugstoreGroups = new HashSet<DrugstoreGroup>();
        }
    
        public int AccountID { get; set; }
        public int RoleID { get; set; }
        public int ProfileID { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsPending { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual AccountProfile AccountProfile { get; set; }
        public virtual Role Role { get; set; }
        public virtual ICollection<District> Districts { get; set; }
        public virtual ICollection<Drugstore> Drugstores { get; set; }
        public virtual ICollection<Drugstore> Drugstores1 { get; set; }
        public virtual ICollection<DrugstoreGroup> DrugstoreGroups { get; set; }
    }
}
