//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryMan
    {
        public DeliveryMan()
        {
            this.DeliverySchedules = new HashSet<DeliverySchedule>();
        }
    
        public int DeliveryManID { get; set; }
        public string FullName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<DeliverySchedule> DeliverySchedules { get; set; }
    }
}
