//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySchedule
    {
        public DeliverySchedule()
        {
            this.DeliveryScheduleDetails = new HashSet<DeliveryScheduleDetail>();
        }
    
        public int DeliveryScheduleID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public int DeliveryManID { get; set; }
        public int Status { get; set; }
    
        public virtual DeliveryMan DeliveryMan { get; set; }
        public virtual ICollection<DeliveryScheduleDetail> DeliveryScheduleDetails { get; set; }
    }
}
