//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrugstoreType
    {
        public DrugstoreType()
        {
            this.DiscountRates = new HashSet<DiscountRate>();
            this.Drugstores = new HashSet<Drugstore>();
        }
    
        public int DrugstoreTypeID { get; set; }
        public string DrugstoreTypeName { get; set; }
    
        public virtual ICollection<DiscountRate> DiscountRates { get; set; }
        public virtual ICollection<Drugstore> Drugstores { get; set; }
    }
}
