//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drugstore
    {
        public Drugstore()
        {
            this.DrugOrders = new HashSet<DrugOrder>();
            this.Payments = new HashSet<Payment>();
        }
    
        public int DrugstoreID { get; set; }
        public string DrugstoreName { get; set; }
        public string Address { get; set; }
        public string Coordinate { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> DrugstoreTypeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> Debt { get; set; }
        public Nullable<int> DistrictID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual District District { get; set; }
        public virtual ICollection<DrugOrder> DrugOrders { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual DrugstoreType DrugstoreType { get; set; }
    }
}
