//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DMPEntities : DbContext
    {
        public DMPEntities()
            : base("name=DMPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountProfile> AccountProfiles { get; set; }
        public virtual DbSet<DeliveryMan> DeliveryMen { get; set; }
        public virtual DbSet<DeliverySchedule> DeliverySchedules { get; set; }
        public virtual DbSet<DeliveryScheduleDetail> DeliveryScheduleDetails { get; set; }
        public virtual DbSet<DiscountRate> DiscountRates { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<Drug> Drugs { get; set; }
        public virtual DbSet<DrugCompany> DrugCompanies { get; set; }
        public virtual DbSet<DrugOrder> DrugOrders { get; set; }
        public virtual DbSet<DrugOrderDetail> DrugOrderDetails { get; set; }
        public virtual DbSet<Drugstore> Drugstores { get; set; }
        public virtual DbSet<DrugstoreGroup> DrugstoreGroups { get; set; }
        public virtual DbSet<DrugstoreType> DrugstoreTypes { get; set; }
        public virtual DbSet<DrugType> DrugTypes { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
    }
}
