//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public Unit()
        {
            this.DrugOrderDetails = new HashSet<DrugOrderDetail>();
            this.Prices = new HashSet<Price>();
        }
    
        public int UnitId { get; set; }
        public string UnitName { get; set; }
    
        public virtual ICollection<DrugOrderDetail> DrugOrderDetails { get; set; }
        public virtual ICollection<Price> Prices { get; set; }
    }
}
